{% set name = "compas_skeleton" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26bcda1273d5228eb4c3684045f80b2c68d7828a4216955af4329335b9e3d702

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - compas

test:
  imports:
    - compas_skeleton
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BlockResearchGroup/compas_skeleton
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Topologically generating mesh from a set of lines and allowing interactive editing.
  doc_url: https://blockresearchgroup.github.io/compas_skeleton/
  dev_url: https://github.com/BlockResearchGroup/compas_skeleton

extra:
  recipe-maintainers:
    - tomvanmele
    - licini
